#ifndef Nachos_protocol_h
#define Nachos_protocol_h

#define NETWORK_SERVER_CONNECT_REQUEST 1
#define NETWORK_SERVER_CONNECT_REPLY   2
#define NETWORK_SERVER_CLOSE_REQUEST 3
#define NETWORK_SERVER_CLOSE_REPLY   4
#define NETWORK_SERVER_CREATELOCK_REQUEST 5
#define NETWORK_SERVER_CREATELOCK_REPLY 6
#define NETWORK_SERVER_DESTROYLOCK_REQUEST 7
#define NETWORK_SERVER_DESTROYLOCK_REPLY   8
#define NETWORK_SERVER_ACQUIRELOCK_REQUEST 9
#define NETWORK_SERVER_ACQUIRELOCK_REPLY   10
#define NETWORK_SERVER_RELEASELOCK_REQUEST 11
#define NETWORK_SERVER_RELEASELOCK_REPLY   12
#define NETWORK_SERVER_CREATECONDITION_REQUEST 13
#define NETWORK_SERVER_CREATECONDITION_REPLY   14
#define NETWORK_SERVER_DESTROYCONDITION_REQUEST 15
#define NETWORK_SERVER_DESTROYCONDITION_REPLY   16
#define NETWORK_SERVER_WAITCONDITION_REQUEST    17
#define NETWORK_SERVER_WAITCONDITION_REPLY      18
#define NETWORK_SERVER_SIGNALCONDITION_REQUEST  19
#define NETWORK_SERVER_SIGNALCONDITION_REPLY    20
#define NETWORK_SERVER_BROADCASTCONDITION_REQUEST   21
#define NETWORK_SERVER_BROADCASTCONDITION_REPLY     22
#define NETWORK_SERVER_CREATEMV_REQUEST 23
#define NETWORK_SERVER_CREATEMV_REPLY   24
#define NETWORK_SERVER_SETMV_REQUEST    25
#define NETWORK_SERVER_SETMV_REPLY      26
#define NETWORK_SERVER_GETMV_REQUEST    27
#define NETWORK_SERVER_GETMV_REPLY  28
#define NETWORK_SERVER_DESTROYMV_REQUEST    29
#define NETWORK_SERVER_DESTROYMV_REPLY  30
#define NETWORK_SERVER_MESSAGESHARE_REQUEST 31
#define NETWORK_SERVER_MESSAGESHARE_REPLY 32
#define NETWORK_SERVER_TEST_REQUEST 99
#define NETWORK_SERVER_TEST_REPLY   100



#endif
