# This is part of a GNU-Makefile, to specify system-dependent 
# parts of the Makefile enviroment.
#
# This gets included as part of the GNU-Makefile used in each of 
# the subdirectories.
#

# To compile Nachos on an SCF Sparc running SunOS 5.4,
# uncomment the next four lines.
HOST = -DHOST_SPARC -DHOST_IS_BIG_ENDIAN -DHOST_SVR4 -DHOST_SunOS5
CPP = /usr/ccs/lib/cpp
CPP_AS_FLAGS = -D_ASM
LDFLAGS = -lsocket -lnsl -L/usr/ucblib -lucb

